jobs:
  stage_0_job_0:
    name: fastrtps cyclonedds warehouse-ros
    runs-on: macos-10.15
    strategy:
      fail-fast: false
    needs: []
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Build ros-humble-fastrtps ros-humble-cyclonedds ros-humble-warehouse-ros
      env:
        ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_API_TOKEN }}
        CURRENT_RECIPES: ros-humble-fastrtps ros-humble-cyclonedds ros-humble-warehouse-ros
      run: |
        export CI=azure
        export GIT_BRANCH=$BUILD_SOURCEBRANCHNAME
        export FEEDSTOCK_NAME=$(basename ${BUILD_REPOSITORY_NAME})
        .scripts/build_osx.sh
name: build_osx
on:
  push:
    branches:
    - buildbranch_osx
