package:
  name: ros-humble-desktop
  version: 0.10.0
source:
  git_url: https://github.com/ros2-gbp/variants-release.git
  git_rev: release/humble/desktop/0.10.0-1
  folder: ros-humble-desktop/src/work

build:
  script:
    sel(win): bld_ament_cmake.bat
    sel(unix): build_ament_cmake.sh
  number: 3
about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - "{{ compiler('cxx') }}"
    - "{{ compiler('c') }}"
    - ninja
    - setuptools
    - sel(unix): make
    - sel(unix): coreutils
    - sel(osx): tapi
    - sel(build_platform != target_platform): pkg-config
    - cmake
    - sel(build_platform != target_platform): python
    - sel(build_platform != target_platform): cross-python_{{ target_platform }}
    - sel(build_platform != target_platform): cython
    - sel(build_platform != target_platform): numpy
  host:
    - numpy
    - pip
    - sel(build_platform == target_platform): pkg-config
    - python
    - ros-humble-ament-cmake
    - ros-humble-ros-environment
    - ros-humble-ros-workspace
    - ros2-distro-mutex 0.3 humble
  run:
    - python
    - ros-humble-action-tutorials-cpp
    - ros-humble-action-tutorials-interfaces
    - ros-humble-action-tutorials-py
    - ros-humble-angles
    - ros-humble-composition
    - ros-humble-demo-nodes-cpp
    - ros-humble-demo-nodes-cpp-native
    - ros-humble-demo-nodes-py
    - ros-humble-depthimage-to-laserscan
    - ros-humble-dummy-map-server
    - ros-humble-dummy-robot-bringup
    - ros-humble-dummy-sensors
    - ros-humble-examples-rclcpp-minimal-action-client
    - ros-humble-examples-rclcpp-minimal-action-server
    - ros-humble-examples-rclcpp-minimal-client
    - ros-humble-examples-rclcpp-minimal-composition
    - ros-humble-examples-rclcpp-minimal-publisher
    - ros-humble-examples-rclcpp-minimal-service
    - ros-humble-examples-rclcpp-minimal-subscriber
    - ros-humble-examples-rclcpp-minimal-timer
    - ros-humble-examples-rclcpp-multithreaded-executor
    - ros-humble-examples-rclpy-executors
    - ros-humble-examples-rclpy-minimal-action-client
    - ros-humble-examples-rclpy-minimal-action-server
    - ros-humble-examples-rclpy-minimal-client
    - ros-humble-examples-rclpy-minimal-publisher
    - ros-humble-examples-rclpy-minimal-service
    - ros-humble-examples-rclpy-minimal-subscriber
    - ros-humble-image-tools
    - ros-humble-intra-process-demo
    - ros-humble-joy
    - ros-humble-lifecycle
    - ros-humble-logging-demo
    - ros-humble-pcl-conversions
    - ros-humble-pendulum-msgs
    - ros-humble-quality-of-service-demo-cpp
    - ros-humble-quality-of-service-demo-py
    - ros-humble-ros-base
    - ros-humble-ros-workspace
    - ros-humble-rqt-common-plugins
    - ros-humble-rviz-default-plugins
    - ros-humble-rviz2
    - ros-humble-teleop-twist-joy
    - ros-humble-teleop-twist-keyboard
    - ros-humble-topic-monitor
    - ros-humble-turtlesim
    - ros2-distro-mutex 0.3 humble
    - sel(osx and x86_64): __osx >={{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
